### ISSUE TITLE
Using element creates a horizontal scroll bar

### ISSUE THREAD

**Issue by jeremiak** [CalMatters/scrolly-photos#5]
When I put the element into a post the page had a horizontal scroll bar. And it wasn't a big one, just a tiny bit of extra scroll.

The fix for now is to add the following CSS to the page where you use `<scrolly-photos>`:

```css
/* style hack to prevent a horizontal scroll bar when using <scrolly-photos> */
html {
  overflow-x: hidden;
}
```
